Update tomlchecker.yml

diff --git a/.github/workflows/tomlchecker.yml b/.github/workflows/tomlchecker.yml
--- a/.github/workflows/tomlchecker.yml
+++ b/.github/workflows/tomlchecker.yml
@@ -1,12 +1,37 @@
+name: TOML Checker
 on:
   push:
-    branches:
-    - master
-  workflow_dispatch:
-name: TOML-Checker
+    paths:
+      - "embeds.toml"
 jobs:
-  TOML-Checker:
+  check_code:
     runs-on: ubuntu-latest
     steps:
-    - name: TOML linter
-      uses: yisonPylkita/gh-action-toml-linter@0.1.3
+      - name: Install java
+        uses: actions/setup-java@v2.3.1
+        with:
+          distribution: 'adopt'
+          java-version: '11'
+          check-latest: false
+
+      - name: Clone repository 
+        uses: actions/checkout@v2
+
+      - name: Download application
+        run: wget 'https://geri.dev/bloom/check.jar'
+
+      - name: 'Verify TOML code'
+        id: verify
+        run: |
+          echo ::set-output name=results::$(java -jar check.jar embeds.toml)
+
+      - name: '✔️ Valid TOML Code Found'
+        run: exit 0
+        if: steps.verify.outputs.results == 'OK'
+
+      - name: '❌ Invalid TOML Code Found'
+        run: |
+          echo ::error::Unable to parse data:
+          echo '::error::${{steps.verify.outputs.results}}'
+          exit 1
+        if: steps.verify.outputs.results != 'OK'
